# Generated by Django 4.1.5 on 2023-07-26 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='duties_bullets',
            field=models.JSONField(blank=True, default=['bullet 1', 'bullet 2', 'bullet 3'], null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='requirements_bullets',
            field=models.JSONField(blank=True, default=['bullet 1', 'bullet 2', 'bullet 3'], null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='requirements_head',
            field=models.TextField(default='bullet'),
            preserve_default=False,
        ),
    ]
