# Generated by Django 4.1.5 on 2023-07-27 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_job_duties_bullets_job_requirements_bullets_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='duties_bullets',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='requirements_bullets',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
