# Generated by Django 4.1.5 on 2023-07-14 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
        ('profiles', '0002_alter_generaluserproflie_phonenumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyuserprofile',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_company', to='company.company'),
        ),
    ]
