# Generated by Django 4.1.5 on 2023-07-19 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_skill_generaluserproflie_about_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='generaluserproflie',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='static/resumes/'),
        ),
    ]
