# Generated by Django 4.1.5 on 2023-07-27 03:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_workexperienceprofile_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userskill',
            name='profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='skill_profile', to='profiles.generaluserproflie'),
            preserve_default=False,
        ),
    ]
