# Generated by Django 4.1.5 on 2023-07-14 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('website', models.URLField(blank=True)),
                ('industry', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('logo', models.ImageField(blank=True, upload_to='static/company/logos')),
                ('address', models.TextField()),
                ('phone_number', models.CharField(default='+263 xxx xxx xxx', max_length=25)),
                ('company_size', models.CharField(max_length=100)),
                ('established_date', models.DateField()),
            ],
        ),
    ]
